### ISSUE TITLE
Configure the make file

### ISSUE THREAD

**Issue by nolangray15** [dlhsiao/code.pyret.org#8]
Edit make file to determine what to build (local vs. web version)

**Comment by dlhsiao** [comment]
Have two build commands to make the two different version of the build folder so that the user doesn't have to change the Pyret (and maybe Mode) variable in the .env each time

**Comment by dlhsiao** [comment]
Hard coded Mode into run.js and main.js since when running `npm run start-web` and `npm run start-app`, we will want to have the path be correct for both without having to change it in `.env`. 

Created config-app.js to oppose config-web.js. Makefile will now copy the correct version to the build folder depending on if `make app-local` or `make web-local` is run. This is reflected in package.json with `npm run build-web` and `npm run build-app`. In `.env`, we now have PYRET_APP and PYRET_WEB instead of just PYRET. beforePyret.js now reads both versions and decides at runtime which one to use by reading MODE from config.js.

I had to delete my build folder and then run the new commands to get it to work as I think PYRET was stored somewhere else in the folder that wasn't getting overwritten when just running the command with the existing folder.

Ready to be merged with horizon. Holding off since this is on the same branch as the installer stuff and that hasn't been completely tested yet.
